### ISSUE TITLE
cmake -- build .  failed

### ISSUE THREAD

**Issue by hy-cn** [OSGeo/proj.4#3641]
cmake -- build .  failed

```c
CMakeFiles/proj_errno_string_test.dir/proj_errno_string_test.cpp.o:(.data.rel.ro+0x10)：undefined reference to‘typeinfo for testing::Test’
CMakeFiles/proj_errno_string_test.dir/proj_errno_string_test.cpp.o:(.data.rel.ro+0x28)：undefined reference to‘typeinfo for testing::Test’
CMakeFiles/proj_errno_string_test.dir/proj_errno_string_test.cpp.o:(.data.rel.ro+0x40)：undefined reference to‘typeinfo for testing::Test’
collect2: error: ld returned 1 exit status
test/unit/CMakeFiles/proj_errno_string_test.dir/build.make:114: recipe for target 'bin/proj_errno_string_test' failed
make[2]: *** [bin/proj_errno_string_test] Error 1
CMakeFiles/Makefile2:1639: recipe for target 'test/unit/CMakeFiles/proj_errno_string_test.dir/all' failed
make[1]: *** [test/unit/CMakeFiles/proj_errno_string_test.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

```
 - PROJ version9.3.0
 - ubuntu18.04

**Comment by rouault** [comment]
I cannot reproduce any build error on a fresh build in a ubuntu:18.04 Docker image. Is it on a clean build ? Which Ubuntu packages are installed on your system ? How did you invoke cmake to configure the project ? Perhaps retry in a clean build directory
